# Generated by Django 3.0.4 on 2020-03-25 12:36

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('o_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Empty Case'), (1, 'X Case'), (2, 'O Case')], default=0), size=3), size=3), default=[[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], size=9)),
                ('big_board', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Empty Case'), (1, 'X Case'), (2, 'O Case')], default=0), default=[0, 0, 0, 0, 0, 0, 0, 0, 0], size=9)),
                ('last_big_case', models.IntegerField(default=-1, null=True)),
                ('last_line_case', models.IntegerField(default=-1, null=True)),
                ('last_case', models.IntegerField(default=-1, null=True)),
                ('player', models.IntegerField(choices=[(1, 'Player X'), (2, 'Player O')], default=1)),
            ],
        ),
    ]
